### ISSUE TITLE
cronjob at 00:00

### ISSUE THREAD

**Issue by PHPGangsta** [WeeJeWel/nginx-with-certbot#1]
Hi,

I just tested your nginx container, and it works very nicely!

I saw that you run the cronjob at 00:00 every day. Lots of people do cronjobs at 00:00, so there is a big peak at services like letsencrypt at 00:00... It would be nice if you could choose a random time of the day to run the cronjob, to lower the peak at letsencrypt. Either by hardcoding just another time (03:48 or whatever), or by using two random numbers while building the image (which might be overkill).

**Comment by WeeJeWel** [comment]
Yeah you're right, but... I'll change it when the people behind Let's Encrypt start complaining :-)

**Comment by PHPGangsta** [comment]
They already do that... See:

> We've had some overload issues at the biggest peak throughout June **at midnight (00:00) UTC**, and it lasts for 15-20 seconds. We're working on various projects to scale and improve that, but those may take some time and **it would be helpful to move load away from that peak**.

https://community.letsencrypt.org/t/brief-overloads-at-midnight-utc-a-request-for-help/179993

> **Why should my Let’s Encrypt (ACME) client run at a random time?**
> - We ask that ACME clients perform routine renewals at random times to avoid spikes in traffic at set times of the day, **such as exactly midnight UTC**, or the first second of each hour or minute.

https://letsencrypt.org/docs/faq/
